/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.imbochfckyeah.projects.calculatorphysical;

import java.awt.Color;

/**
 *
 * @author joshu
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    Color DefaultColor,ClickedColor;
    public dashboard() {
        initComponents();
        DefaultColor = new Color(0,180,216);
        ClickedColor = new Color(0,119,182);
        panelRound2.setBackground(ClickedColor);
        portada view = new portada();
        container.add(view).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelRound1 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        panelRound2 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        dash = new javax.swing.JLabel();
        panelRound3 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        convertlong = new javax.swing.JLabel();
        panelRound4 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        proyectiles = new javax.swing.JLabel();
        panelRound5 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        datosperfil = new javax.swing.JLabel();
        panelRound6 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        salir = new javax.swing.JLabel();
        panelRound9 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        sumavectores = new javax.swing.JLabel();
        panelRound10 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        convertmasa = new javax.swing.JLabel();
        panelRound11 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        converttime = new javax.swing.JLabel();
        container = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(199, 249, 204));
        setResizable(false);
        setSize(new java.awt.Dimension(1215, 641));

        background.setBackground(new java.awt.Color(202, 240, 248));

        panelRound1.setBackground(new java.awt.Color(0, 180, 216));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);

        panelRound2.setBackground(new java.awt.Color(0, 180, 216));
        panelRound2.setRoundBottomLeft(10);
        panelRound2.setRoundBottomRight(10);
        panelRound2.setRoundTopLeft(10);
        panelRound2.setRoundTopRight(10);

        dash.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        dash.setForeground(new java.awt.Color(255, 255, 255));
        dash.setIcon(new javax.swing.ImageIcon("C:\\Users\\joshu\\OneDrive\\1 semestre\\NetBeansProjects\\calculatorPHYSICAL\\resources\\outline_dashboard_white_24dp.png")); // NOI18N
        dash.setText("DASHBOARD");
        dash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(0, 180, 216));
        panelRound3.setRoundBottomLeft(10);
        panelRound3.setRoundBottomRight(10);
        panelRound3.setRoundTopLeft(10);
        panelRound3.setRoundTopRight(10);

        convertlong.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        convertlong.setForeground(new java.awt.Color(255, 255, 255));
        convertlong.setIcon(new javax.swing.ImageIcon("resources/outline_square_foot_white_24dp.png")); // NOI18N
        convertlong.setText("Longitud");
        convertlong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                convertlongMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convertlong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convertlong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound4.setBackground(new java.awt.Color(0, 180, 216));
        panelRound4.setRoundBottomLeft(10);
        panelRound4.setRoundBottomRight(10);
        panelRound4.setRoundTopLeft(10);
        panelRound4.setRoundTopRight(10);

        proyectiles.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        proyectiles.setForeground(new java.awt.Color(255, 255, 255));
        proyectiles.setIcon(new javax.swing.ImageIcon("C:\\Users\\joshu\\OneDrive\\1 semestre\\NetBeansProjects\\calculatorPHYSICAL\\resources\\outline_airline_stops_white_24dp.png")); // NOI18N
        proyectiles.setText("Proyectiles");
        proyectiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                proyectilesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proyectiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proyectiles)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound5.setBackground(new java.awt.Color(0, 180, 216));
        panelRound5.setRoundBottomLeft(10);
        panelRound5.setRoundBottomRight(10);
        panelRound5.setRoundTopLeft(10);
        panelRound5.setRoundTopRight(10);

        datosperfil.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        datosperfil.setForeground(new java.awt.Color(255, 255, 255));
        datosperfil.setIcon(new javax.swing.ImageIcon("C:\\Users\\joshu\\OneDrive\\1 semestre\\NetBeansProjects\\calculatorPHYSICAL\\resources\\outline_account_circle_white_24dp.png")); // NOI18N
        datosperfil.setText("Datos estudiante");
        datosperfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                datosperfilMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosperfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosperfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound6.setBackground(new java.awt.Color(0, 180, 216));
        panelRound6.setRoundBottomLeft(10);
        panelRound6.setRoundBottomRight(10);
        panelRound6.setRoundTopLeft(10);
        panelRound6.setRoundTopRight(10);

        salir.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon("C:\\Users\\joshu\\OneDrive\\1 semestre\\NetBeansProjects\\calculatorPHYSICAL\\resources\\outline_logout_white_24dp.png")); // NOI18N
        salir.setText("SALIR");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound9.setBackground(new java.awt.Color(0, 180, 216));
        panelRound9.setRoundBottomLeft(10);
        panelRound9.setRoundBottomRight(10);
        panelRound9.setRoundTopLeft(10);
        panelRound9.setRoundTopRight(10);

        sumavectores.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        sumavectores.setForeground(new java.awt.Color(255, 255, 255));
        sumavectores.setIcon(new javax.swing.ImageIcon("C:\\Users\\joshu\\OneDrive\\1 semestre\\NetBeansProjects\\calculatorPHYSICAL\\resources\\outline_functions_white_24dp.png")); // NOI18N
        sumavectores.setText("Suma de vectores");
        sumavectores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sumavectoresMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sumavectores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sumavectores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound10.setBackground(new java.awt.Color(0, 180, 216));
        panelRound10.setRoundBottomLeft(10);
        panelRound10.setRoundBottomRight(10);
        panelRound10.setRoundTopLeft(10);
        panelRound10.setRoundTopRight(10);

        convertmasa.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        convertmasa.setForeground(new java.awt.Color(255, 255, 255));
        convertmasa.setIcon(new javax.swing.ImageIcon("C:\\Users\\joshu\\OneDrive\\1 semestre\\NetBeansProjects\\calculatorPHYSICAL\\resources\\outline_scale_white_24dp.png")); // NOI18N
        convertmasa.setText("Masa");
        convertmasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                convertmasaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound10Layout = new javax.swing.GroupLayout(panelRound10);
        panelRound10.setLayout(panelRound10Layout);
        panelRound10Layout.setHorizontalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convertmasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound10Layout.setVerticalGroup(
            panelRound10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(convertmasa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRound11.setBackground(new java.awt.Color(0, 180, 216));
        panelRound11.setRoundBottomLeft(10);
        panelRound11.setRoundBottomRight(10);
        panelRound11.setRoundTopLeft(10);
        panelRound11.setRoundTopRight(10);

        converttime.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        converttime.setForeground(new java.awt.Color(255, 255, 255));
        converttime.setIcon(new javax.swing.ImageIcon("C:\\Users\\joshu\\OneDrive\\1 semestre\\NetBeansProjects\\calculatorPHYSICAL\\resources\\outline_update_white_24dp.png")); // NOI18N
        converttime.setText("Tiempo");
        converttime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                converttimeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound11Layout = new javax.swing.GroupLayout(panelRound11);
        panelRound11.setLayout(panelRound11Layout);
        panelRound11Layout.setHorizontalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(converttime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound11Layout.setVerticalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(converttime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        container.setBackground(new java.awt.Color(144, 224, 239));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(container))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1231, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void convertlongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertlongMousePressed
        // TODO add your handling code here:
        panelRound2.setBackground(DefaultColor);
        panelRound3.setBackground(ClickedColor);
        panelRound4.setBackground(DefaultColor);
        panelRound5.setBackground(DefaultColor);
        panelRound6.setBackground(DefaultColor);
        panelRound9.setBackground(DefaultColor);
        panelRound10.setBackground(DefaultColor);
        panelRound11.setBackground(DefaultColor);
        
        LONGconvert view = new LONGconvert();
        container.removeAll();
        container.add(view).setVisible(true);
        
    }//GEN-LAST:event_convertlongMousePressed

    private void proyectilesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proyectilesMousePressed
        // TODO add your handling code here:
        panelRound2.setBackground(DefaultColor);
        panelRound3.setBackground(DefaultColor);
        panelRound4.setBackground(ClickedColor);
        panelRound5.setBackground(DefaultColor);
        panelRound6.setBackground(DefaultColor);
        panelRound9.setBackground(DefaultColor);
        panelRound10.setBackground(DefaultColor);
        panelRound11.setBackground(DefaultColor);
        
        MOVproyectiles view = new MOVproyectiles();
        container.removeAll();
        container.add(view).setVisible(true);
    }//GEN-LAST:event_proyectilesMousePressed

    private void datosperfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datosperfilMousePressed
        // TODO add your handling code here:
        panelRound2.setBackground(DefaultColor);
        panelRound3.setBackground(DefaultColor);
        panelRound4.setBackground(DefaultColor);
        panelRound5.setBackground(ClickedColor);
        panelRound6.setBackground(DefaultColor);
        panelRound9.setBackground(DefaultColor);
        panelRound10.setBackground(DefaultColor);
        panelRound11.setBackground(DefaultColor);
        
        myperfil view = new myperfil();
        container.removeAll();
        container.add(view).setVisible(true);
    }//GEN-LAST:event_datosperfilMousePressed

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        // TODO add your handling code here:
        panelRound2.setBackground(DefaultColor);
        panelRound3.setBackground(DefaultColor);
        panelRound4.setBackground(DefaultColor);
        panelRound5.setBackground(DefaultColor);
        panelRound6.setBackground(ClickedColor);
        panelRound9.setBackground(DefaultColor);
        panelRound10.setBackground(DefaultColor);
        panelRound11.setBackground(DefaultColor);
        
        this.dispose();
    }//GEN-LAST:event_salirMousePressed

    private void dashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMousePressed
        // TODO add your handling code here:
        panelRound2.setBackground(ClickedColor);
        panelRound3.setBackground(DefaultColor);
        panelRound4.setBackground(DefaultColor);
        panelRound5.setBackground(DefaultColor);
        panelRound6.setBackground(DefaultColor);
        panelRound9.setBackground(DefaultColor);
        panelRound10.setBackground(DefaultColor);
        panelRound11.setBackground(DefaultColor);
        
        portada view = new portada();
        container.removeAll();
        container.add(view).setVisible(true);
    }//GEN-LAST:event_dashMousePressed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_salirMouseClicked

    private void dashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashMouseClicked

    private void sumavectoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumavectoresMousePressed
        // TODO add your handling code here:
        panelRound2.setBackground(DefaultColor);
        panelRound3.setBackground(DefaultColor);
        panelRound4.setBackground(DefaultColor);
        panelRound5.setBackground(DefaultColor);
        panelRound6.setBackground(DefaultColor);
        panelRound9.setBackground(ClickedColor);
        panelRound10.setBackground(DefaultColor);
        panelRound11.setBackground(DefaultColor);
        
        SUMAvectores view = new SUMAvectores();
        container.removeAll();
        container.add(view).setVisible(true);
    }//GEN-LAST:event_sumavectoresMousePressed

    private void convertmasaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertmasaMousePressed
        // TODO add your handling code here:
        panelRound2.setBackground(DefaultColor);
        panelRound3.setBackground(DefaultColor);
        panelRound4.setBackground(DefaultColor);
        panelRound5.setBackground(DefaultColor);
        panelRound6.setBackground(DefaultColor);
        panelRound9.setBackground(DefaultColor);
        panelRound10.setBackground(ClickedColor);
        panelRound11.setBackground(DefaultColor);
        
        MASAconvert view = new MASAconvert();
        container.removeAll();
        container.add(view).setVisible(true);
    }//GEN-LAST:event_convertmasaMousePressed

    private void converttimeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_converttimeMousePressed
        // TODO add your handling code here:
        panelRound2.setBackground(DefaultColor);
        panelRound3.setBackground(DefaultColor);
        panelRound4.setBackground(DefaultColor);
        panelRound5.setBackground(DefaultColor);
        panelRound6.setBackground(DefaultColor);
        panelRound9.setBackground(DefaultColor);
        panelRound10.setBackground(DefaultColor);
        panelRound11.setBackground(ClickedColor);
        TIMEconvert view = new TIMEconvert();
        container.removeAll();
        container.add(view).setVisible(true);
    }//GEN-LAST:event_converttimeMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JDesktopPane container;
    private javax.swing.JLabel convertlong;
    private javax.swing.JLabel convertmasa;
    private javax.swing.JLabel converttime;
    private javax.swing.JLabel dash;
    private javax.swing.JLabel datosperfil;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound1;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound10;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound11;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound2;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound3;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound4;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound5;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound6;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound9;
    private javax.swing.JLabel proyectiles;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel sumavectores;
    // End of variables declaration//GEN-END:variables
}
