/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.imbochfckyeah.projects.calculatorphysical;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author joshu
 */
public class LONGconvert extends javax.swing.JInternalFrame {

    /**
     * Creates new form UNITconvert
     */
    public LONGconvert() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        metros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kilometros = new javax.swing.JTextField();
        millas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pies = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        centimetros = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pulgadas = new javax.swing.JTextField();
        panelRound1 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        limpiar = new javax.swing.JLabel();
        panelRound3 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        calcular = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(144, 224, 239));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LONGITUD");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresa un dato");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Metros");

        metros.setBackground(new java.awt.Color(0, 180, 216));
        metros.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        metros.setForeground(new java.awt.Color(255, 255, 255));
        metros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        metros.setText("0");
        metros.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kilómetros");

        kilometros.setBackground(new java.awt.Color(0, 180, 216));
        kilometros.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        kilometros.setForeground(new java.awt.Color(255, 255, 255));
        kilometros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kilometros.setText("0");
        kilometros.setBorder(null);

        millas.setBackground(new java.awt.Color(0, 180, 216));
        millas.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        millas.setForeground(new java.awt.Color(255, 255, 255));
        millas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        millas.setText("0");
        millas.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Millas");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pies");

        pies.setBackground(new java.awt.Color(0, 180, 216));
        pies.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        pies.setForeground(new java.awt.Color(255, 255, 255));
        pies.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pies.setText("0");
        pies.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Centímetros");

        centimetros.setBackground(new java.awt.Color(0, 180, 216));
        centimetros.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        centimetros.setForeground(new java.awt.Color(255, 255, 255));
        centimetros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        centimetros.setText("0");
        centimetros.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pulgadas");

        pulgadas.setBackground(new java.awt.Color(0, 180, 216));
        pulgadas.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        pulgadas.setForeground(new java.awt.Color(255, 255, 255));
        pulgadas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pulgadas.setText("0");
        pulgadas.setBorder(null);

        panelRound1.setBackground(new java.awt.Color(0, 119, 182));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        limpiar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limpiar.setText("Limpiar");
        limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound3.setBackground(new java.awt.Color(0, 119, 182));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        calcular.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        calcular.setForeground(new java.awt.Color(255, 255, 255));
        calcular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calcular.setText("Calcular");
        calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calcularMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kilometros)
                            .addComponent(millas)
                            .addComponent(metros, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(pies, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(centimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(pulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(metros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pies, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(centimetros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(millas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1010, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularMousePressed
        // TODO add your handling code here:
        double mt, km, mi, ft, cm, in, r1, r2, r3, r4, r5;
        
        mt = Integer.parseInt(metros.getText());
        km = Integer.parseInt(kilometros.getText());
        mi = Integer.parseInt(millas.getText());
        ft = Integer.parseInt(pies.getText());
        cm = Integer.parseInt(centimetros.getText());
        in = Integer.parseInt(pulgadas.getText());
        //metros
        if(mt!=0 && km==0 && mi==0 && ft==0 && cm==0 && in==0){
            r1 = mt/1000;
            r2 = mt/1609;
            r3 = mt*3.281;
            r4 = mt*100;
            r5 = mt*39.37;
            kilometros.setText(""+r1+" km");
            millas.setText(""+r2+" mi");
            pies.setText(""+r3+" ft");
            centimetros.setText(""+r4+" cm");
            pulgadas.setText(""+r5+" in");
        }else if(mt==0 && km!=0 && mi==0 && ft==0 && cm==0 && in==0){
            r1 = km*1000;
            r2 = km/1.609;
            r3 = km*3281;
            r4 = km*100000;
            r5 = km*39370;
            metros.setText(""+r1+" mt");
            millas.setText(""+r2+" mi");
            pies.setText(""+r3+" ft");
            centimetros.setText(""+r4+" cm");
            pulgadas.setText(""+r5+" in");
        }else if(mt==0 && km==0 && mi!=0 && ft==0 && cm==0 && in==0){
            r1 = mi*1609;
            r2 = mi*1.609;
            r3 = mi*5280;
            r4 = mi*160934;
            r5 = mi*63360;
            metros.setText(""+r1+" mt");
            kilometros.setText(""+r2+" km");
            pies.setText(""+r3+" ft");
            centimetros.setText(""+r4+" cm");
            pulgadas.setText(""+r5+" in");
        }else if(mt==0 && km==0 && mi==0 && ft!=0 && cm==0 && in==0){
            r1 = ft/3.281;
            r2 = ft/3281;
            r3 = ft/5280;
            r4 = ft*30.48;
            r5 = ft*12;
            metros.setText(""+r1+" mt");
            kilometros.setText(""+r2+" km");
            millas.setText(""+r3+" mi");
            centimetros.setText(""+r4+" cm");
            pulgadas.setText(""+r5+" in");
        }else if(mt==0 && km==0 && mi==0 && ft==0 && cm!=0 && in==0){
            r1 = cm/100;
            r2 = cm/100000;
            r3 = cm/160934;
            r4 = cm/30.48;
            r5 = cm/2.54;
            metros.setText(""+r1+" mt");
            kilometros.setText(""+r2+" km");
            millas.setText(""+r3+" mi");
            pies.setText(""+r4+" ft");
            pulgadas.setText(""+r5+" in");
        }else if(mt==0 && km==0 && mi==0 && ft==0 && cm==0 && in!=0){
            r1 = in/39.37;
            r2 = in/39370;
            r3 = in/63360;
            r4 = in/12;
            r5 = in*2.54;
            metros.setText(""+r1+" mt");
            kilometros.setText(""+r2+" km");
            millas.setText(""+r3+" mi");
            pies.setText(""+r4+" ft");
            centimetros.setText(""+r5+" cm");
        }else if(mt==0 && km==0 && mi==0 && ft==0 && cm==0 && in==0){
            JOptionPane.showMessageDialog(this, "Por favor introduce un valor, en algún campo.");
        }
        
    }//GEN-LAST:event_calcularMousePressed

    private void limpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarMousePressed
        // TODO add your handling code here:
            metros.setText("0");
            kilometros.setText("0");
            millas.setText("0");
            pies.setText("0");
            centimetros.setText("0");
            pulgadas.setText("0");
    }//GEN-LAST:event_limpiarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel calcular;
    private javax.swing.JTextField centimetros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField kilometros;
    private javax.swing.JLabel limpiar;
    private javax.swing.JTextField metros;
    private javax.swing.JTextField millas;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound1;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound3;
    private javax.swing.JTextField pies;
    private javax.swing.JTextField pulgadas;
    // End of variables declaration//GEN-END:variables
}
