/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.imbochfckyeah.projects.calculatorphysical;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.text.DecimalFormat;

/**
 *
 * @author joshu
 */
public class SUMAvectores extends javax.swing.JInternalFrame {

    /**
     * Creates new form SUMAvectores
     */
    public SUMAvectores() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    String vectores, posiciones; int a,b;
    double [] mag, ang, magX, magY;
    double magSX, magSY, magR, angR;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sumarv = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        volvers = new javax.swing.JLabel();
        panelRound4 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        start = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        magnitud = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        direccion = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        sumatorias = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        vResultante = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        dResultante = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(144, 224, 239));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUMA DE VECTORES");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Presiona el botón de empezar a sumar.");

        sumarv.setBackground(new java.awt.Color(0, 119, 182));
        sumarv.setRoundBottomLeft(20);
        sumarv.setRoundBottomRight(20);
        sumarv.setRoundTopLeft(20);
        sumarv.setRoundTopRight(20);

        volvers.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        volvers.setForeground(new java.awt.Color(255, 255, 255));
        volvers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volvers.setText("Limpiar");
        volvers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volversMousePressed(evt);
            }
        });

        javax.swing.GroupLayout sumarvLayout = new javax.swing.GroupLayout(sumarv);
        sumarv.setLayout(sumarvLayout);
        sumarvLayout.setHorizontalGroup(
            sumarvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumarvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volvers, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        sumarvLayout.setVerticalGroup(
            sumarvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumarvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volvers, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound4.setBackground(new java.awt.Color(0, 119, 182));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        start.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        start.setText("¡Empezar a sumar!");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        magnitud.setEditable(false);
        magnitud.setBackground(new java.awt.Color(0, 180, 216));
        magnitud.setColumns(20);
        magnitud.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        magnitud.setForeground(new java.awt.Color(255, 255, 255));
        magnitud.setRows(5);
        jScrollPane1.setViewportView(magnitud);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        direccion.setEditable(false);
        direccion.setBackground(new java.awt.Color(0, 180, 216));
        direccion.setColumns(20);
        direccion.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setRows(5);
        jScrollPane2.setViewportView(direccion);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setToolTipText("");
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        sumatorias.setEditable(false);
        sumatorias.setBackground(new java.awt.Color(0, 180, 216));
        sumatorias.setColumns(20);
        sumatorias.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        sumatorias.setForeground(new java.awt.Color(255, 255, 255));
        sumatorias.setRows(5);
        jScrollPane3.setViewportView(sumatorias);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        vResultante.setEditable(false);
        vResultante.setBackground(new java.awt.Color(0, 180, 216));
        vResultante.setColumns(20);
        vResultante.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        vResultante.setForeground(new java.awt.Color(255, 255, 255));
        vResultante.setRows(5);
        jScrollPane4.setViewportView(vResultante);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setToolTipText("");
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        dResultante.setEditable(false);
        dResultante.setBackground(new java.awt.Color(0, 180, 216));
        dResultante.setColumns(20);
        dResultante.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        dResultante.setForeground(new java.awt.Color(255, 255, 255));
        dResultante.setRows(5);
        jScrollPane5.setViewportView(dResultante);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Magnnitud");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Direccion");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Σ magnitudes");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VR");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("θR");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(762, 762, 762)
                        .addComponent(sumarv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(80, 80, 80)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(82, 82, 82)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addGap(86, 86, 86))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(sumarv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1010, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void volversMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volversMousePressed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_volversMousePressed

    private void startMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMousePressed
        // TODO add your handling code here:
        String num = JOptionPane.showInputDialog("¿Cuantos vectore quieres sumar? (hasta 4 vectores)");
        int numv = Integer.parseInt(num);
        
        if(numv==2 || numv == 3 || numv == 4){
            sumaVec(numv);
        }else{
            JOptionPane.showMessageDialog(this, "Solo puedes sumar de 2 a 4 vectores, intenta nuevamente.");
        }
    }//GEN-LAST:event_startMousePressed

    private void sumaVec(int numV){

        mag = new double[numV];
        ang = new double[numV];
        magX = new double[numV];
        magY = new double[numV];

        String pattern = "######.#";
        DecimalFormat decimalFormat = new DecimalFormat(pattern);
        String vec = "";

        //Pedir datos
        for(b=0; b<numV; b++){
            
            if(b==0){
                vec = "A";
            }else if(b==1){
                vec = "B";
            }else if(b==2){
                vec = "C";
            }else if(b==3){
                vec = "D";
            }

            mag[b] = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el valor de la magnitud del vector " + vec));
            ang[b] = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el valor del ángulo del vector " + vec));

            magnitud.append(vec + " = " + mag[b]+"\n");
            direccion.append(vec + " = " + ang[b]+"°\n");
        }

        //Calcular Magnitudes de X y de Y
        int cont = 0;
        magSX = 0;
        magSY = 0;
        for(Double x: mag){
            double angTemp = Math.toRadians(ang[cont]);
            magX[cont] = x * Math.cos(angTemp);
            magY[cont] = x * Math.sin(angTemp);

            magSX = magSX + magX[cont];
            magSY = magSY + magY[cont];

            cont = cont + 1;
        }

        magSX = Double.parseDouble(decimalFormat.format(magSX));
        magSY = Double.parseDouble(decimalFormat.format(magSY));

        sumatorias.append("ΣX = " + magSX + "\n" + "ΣY = " + magSY);

        //Resultantes
        magR = Math.sqrt((Math.pow(magSX, 2) + Math.pow(magSY, 2)));
        angR = Math.toDegrees(Math.atan((magSY/magSX)));

        vResultante.append("VR = " + decimalFormat.format(magR));
        dResultante.append("θR = " + decimalFormat.format(angR));
    }


    private void limpiar(){
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        magnitud.setText("");
        direccion.setText("");
        sumatorias.setText("");
        vResultante.setText("");
        dResultante.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextArea dResultante;
    private javax.swing.JTextArea direccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea magnitud;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound4;
    private javax.swing.JLabel start;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound sumarv;
    private javax.swing.JTextArea sumatorias;
    private javax.swing.JTextArea vResultante;
    private javax.swing.JLabel volvers;
    // End of variables declaration//GEN-END:variables
}
