/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.imbochfckyeah.projects.calculatorphysical;

import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author joshu
 */
public class SUMAvectores extends javax.swing.JInternalFrame {

    /**
     * Creates new form SUMAvectores
     */
    public SUMAvectores() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        //
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        vector1.setVisible(false);
        vector2.setVisible(false);
        vector3.setVisible(false);
        vector4.setVisible(false);
        vectoresultante.setVisible(false);
        //
    }

    String vectores, posiciones; int a,b; int [] v1, v2, v3, v4, vr;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sumarv = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        volvers = new javax.swing.JLabel();
        panelRound4 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        start = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vector1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        vector2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        vector3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        vector4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        vectoresultante = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(144, 224, 239));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUMA DE VECTORES");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Presiona el botón de empezar a sumar.");

        sumarv.setBackground(new java.awt.Color(0, 119, 182));
        sumarv.setRoundBottomLeft(20);
        sumarv.setRoundBottomRight(20);
        sumarv.setRoundTopLeft(20);
        sumarv.setRoundTopRight(20);

        volvers.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        volvers.setForeground(new java.awt.Color(255, 255, 255));
        volvers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volvers.setText("Limpiar");
        volvers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volversMousePressed(evt);
            }
        });

        javax.swing.GroupLayout sumarvLayout = new javax.swing.GroupLayout(sumarv);
        sumarv.setLayout(sumarvLayout);
        sumarvLayout.setHorizontalGroup(
            sumarvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumarvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volvers, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        sumarvLayout.setVerticalGroup(
            sumarvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sumarvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volvers, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound4.setBackground(new java.awt.Color(0, 119, 182));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        start.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        start.setText("¡Empezar a sumar!");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        vector1.setEditable(false);
        vector1.setBackground(new java.awt.Color(0, 180, 216));
        vector1.setColumns(20);
        vector1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        vector1.setForeground(new java.awt.Color(255, 255, 255));
        vector1.setRows(5);
        jScrollPane1.setViewportView(vector1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        vector2.setEditable(false);
        vector2.setBackground(new java.awt.Color(0, 180, 216));
        vector2.setColumns(20);
        vector2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        vector2.setForeground(new java.awt.Color(255, 255, 255));
        vector2.setRows(5);
        jScrollPane2.setViewportView(vector2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setToolTipText("");
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        vector3.setEditable(false);
        vector3.setBackground(new java.awt.Color(0, 180, 216));
        vector3.setColumns(20);
        vector3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        vector3.setForeground(new java.awt.Color(255, 255, 255));
        vector3.setRows(5);
        jScrollPane3.setViewportView(vector3);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setToolTipText("");
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        vector4.setEditable(false);
        vector4.setBackground(new java.awt.Color(0, 180, 216));
        vector4.setColumns(20);
        vector4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        vector4.setForeground(new java.awt.Color(255, 255, 255));
        vector4.setRows(5);
        jScrollPane4.setViewportView(vector4);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setToolTipText("");
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        vectoresultante.setEditable(false);
        vectoresultante.setBackground(new java.awt.Color(0, 180, 216));
        vectoresultante.setColumns(20);
        vectoresultante.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        vectoresultante.setForeground(new java.awt.Color(255, 255, 255));
        vectoresultante.setRows(5);
        jScrollPane5.setViewportView(vectoresultante);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel5");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(762, 762, 762)
                        .addComponent(sumarv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(80, 80, 80)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(82, 82, 82)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                .addGap(86, 86, 86))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(sumarv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1010, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void volversMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volversMousePressed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_volversMousePressed

    private void startMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMousePressed
        // TODO add your handling code here:
        String num = JOptionPane.showInputDialog("¿Cuantos vectore quieres sumar? (hasta 4 vectores)");
        int numv = Integer.parseInt(num);
        
        if(numv==2){
            dosvectores();
        }else if(numv==3){
            tresvectores();
        }else if(numv==4){
            cuatrovectores();
        }else{
            JOptionPane.showMessageDialog(this, "Solo puedes sumar de 2 a 4 vectores, intenta nuevamente.");
        }
    }//GEN-LAST:event_startMousePressed

    private void dosvectores(){
       
        vectores = JOptionPane.showInputDialog("¿Cuantas posiciones tienen cada vector?");
        a = Integer.parseInt(vectores);

        jLabel8.setVisible(true);
        jLabel8.setText("El tamano de los vectores es de "+vectores+" posiciones.");
        
        //
        jLabel3.setVisible(true);
        jLabel3.setText("A");
        jLabel4.setVisible(true);
        jLabel4.setText("B");
        jLabel7.setVisible(true);
        jLabel7.setText("C");
        vector1.setVisible(true);
        vector2.setVisible(true);
        vectoresultante.setVisible(true);
        //
        
        v1 = new int[a];
        v2 = new int[a];
        vr = new int[a];
        
        for(b=0; b<a; b++){
            v1[b] = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el valor "+(b+1)+" en la posicion "+(b+1)+" del vector A"));
            posiciones = Integer.toString(v1[b]);
            vector1.append(posiciones+"\n");
        }
        for(b=0; b<a; b++){
            v2[b] = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el valor "+(b+1)+" en la posicion "+(b+1)+" del vector B"));
            posiciones = Integer.toString(v2[b]);
            vector2.append(posiciones+"\n");
        }
        for(b=0; b<a; b++){
            vr[b] = v1[b]+v2[b];
            posiciones = Integer.toString(vr[b]);
            vectoresultante.append(Integer.toString(v1[b])+" + "+Integer.toString(v2[b])+" = "+posiciones+"\n");
        }
    }
    
    private void tresvectores(){
       
        vectores = JOptionPane.showInputDialog("¿Cuantas posiciones tienen cada vector?");
        a = Integer.parseInt(vectores);

        jLabel8.setVisible(true);
        jLabel8.setText("El tamano de los vectores es de "+vectores+" posiciones.");
        
        //
        jLabel3.setVisible(true);
        jLabel3.setText("A");
        jLabel4.setVisible(true);
        jLabel4.setText("B");
        jLabel5.setVisible(true);
        jLabel5.setText("C");
        jLabel7.setVisible(true);
        jLabel7.setText("D");
        vector1.setVisible(true);
        vector2.setVisible(true);
        vector3.setVisible(true);
        vectoresultante.setVisible(true);
        //
        
        v1 = new int[a];
        v2 = new int[a];
        v3 = new int[a];
        vr = new int[a];
        
        for(b=0; b<a; b++){
            v1[b] = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el valor "+(b+1)+" en la posicion "+(b+1)+" del vector A"));
            posiciones = Integer.toString(v1[b]);
            vector1.append(posiciones+"\n");
        }
        for(b=0; b<a; b++){
            v2[b] = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el valor "+(b+1)+" en la posicion "+(b+1)+" del vector B"));
            posiciones = Integer.toString(v2[b]);
            vector2.append(posiciones+"\n");
        }
        for(b=0; b<a; b++){
            v3[b] = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el valor "+(b+1)+" en la posicion "+(b+1)+" del vector C"));
            posiciones = Integer.toString(v3[b]);
            vector3.append(posiciones+"\n");
        }
        for(b=0; b<a; b++){
            vr[b] = v1[b]+v2[b]+v3[b];
            posiciones = Integer.toString(vr[b]);
            vectoresultante.append(Integer.toString(v1[b])+" + "+Integer.toString(v2[b])+" + "+Integer.toString(v3[b])+" = "+posiciones+"\n");
        }
    }
    
    private void cuatrovectores(){
       
        vectores = JOptionPane.showInputDialog("¿Cuantas posiciones tienen cada vector?");
        a = Integer.parseInt(vectores);

        jLabel8.setVisible(true);
        jLabel8.setText("El tamano de los vectores es de "+vectores+" posiciones.");
        
        //
        jLabel3.setVisible(true);
        jLabel3.setText("A");
        jLabel4.setVisible(true);
        jLabel4.setText("B");
        jLabel5.setVisible(true);
        jLabel5.setText("C");
        jLabel6.setVisible(true);
        jLabel6.setText("D");
        jLabel7.setVisible(true);
        jLabel7.setText("E");
        vector1.setVisible(true);
        vector2.setVisible(true);
        vector3.setVisible(true);
        vector4.setVisible(true);
        vectoresultante.setVisible(true);
        //
        
        v1 = new int[a];
        v2 = new int[a];
        v3 = new int[a];
        v4 = new int[a];
        vr = new int[a];
        
        for(b=0; b<a; b++){
            v1[b] = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el valor "+(b+1)+" en la posicion "+(b+1)+" del vector A"));
            posiciones = Integer.toString(v1[b]);
            vector1.append(posiciones+"\n");
        }
        for(b=0; b<a; b++){
            v2[b] = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el valor "+(b+1)+" en la posicion "+(b+1)+" del vector B"));
            posiciones = Integer.toString(v2[b]);
            vector2.append(posiciones+"\n");
        }
        for(b=0; b<a; b++){
            v3[b] = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el valor "+(b+1)+" en la posicion "+(b+1)+" del vector C"));
            posiciones = Integer.toString(v3[b]);
            vector3.append(posiciones+"\n");
        }
        for(b=0; b<a; b++){
            v4[b] = Integer.parseInt(JOptionPane.showInputDialog("Ingresa el valor "+(b+1)+" en la posicion "+(b+1)+" del vector D"));
            posiciones = Integer.toString(v4[b]);
            vector4.append(posiciones+"\n");
        }
        for(b=0; b<a; b++){
            vr[b] = v1[b]+v2[b]+v3[b]+v4[b];
            posiciones = Integer.toString(vr[b]);
            vectoresultante.append(Integer.toString(v1[b])+" + "+Integer.toString(v2[b])+" + "+Integer.toString(v3[b])+" + "+Integer.toString(v4[b])+" = "+posiciones+"\n");
        }
    }
    
    private void limpiar(){
    jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("");
        vector1.setText("");
        vector2.setText("");
        vector3.setText("");
        vector4.setText("");
        vectoresultante.setText("");
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        vector1.setVisible(false);
        vector2.setVisible(false);
        vector3.setVisible(false);
        vector4.setVisible(false);
        vectoresultante.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound4;
    private javax.swing.JLabel start;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound sumarv;
    private javax.swing.JTextArea vector1;
    private javax.swing.JTextArea vector2;
    private javax.swing.JTextArea vector3;
    private javax.swing.JTextArea vector4;
    private javax.swing.JTextArea vectoresultante;
    private javax.swing.JLabel volvers;
    // End of variables declaration//GEN-END:variables
}
