/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.imbochfckyeah.projects.calculatorphysical;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author joshu
 */
public class TIMEconvert extends javax.swing.JInternalFrame {

    /**
     * Creates new form UNITconvert
     */
    public TIMEconvert() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        segundo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        minuto = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        Horas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        panelRound1 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        limpiar = new javax.swing.JLabel();
        panelRound3 = new com.imbochfckyeah.projects.calculatorphysical.PanelRound();
        calcular = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(144, 224, 239));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIEMPO");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresa un dato");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Segundos");

        segundo.setBackground(new java.awt.Color(0, 180, 216));
        segundo.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        segundo.setForeground(new java.awt.Color(255, 255, 255));
        segundo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        segundo.setText("0");
        segundo.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Minutos");

        minuto.setBackground(new java.awt.Color(0, 180, 216));
        minuto.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        minuto.setForeground(new java.awt.Color(255, 255, 255));
        minuto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minuto.setText("0");
        minuto.setBorder(null);

        hora.setBackground(new java.awt.Color(0, 180, 216));
        hora.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        hora.setForeground(new java.awt.Color(255, 255, 255));
        hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        hora.setText("0");
        hora.setBorder(null);

        Horas.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Horas.setForeground(new java.awt.Color(255, 255, 255));
        Horas.setText("Horas");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Días");

        dia.setBackground(new java.awt.Color(0, 180, 216));
        dia.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        dia.setForeground(new java.awt.Color(255, 255, 255));
        dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dia.setText("0");
        dia.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Años");

        ano.setBackground(new java.awt.Color(0, 180, 216));
        ano.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        ano.setForeground(new java.awt.Color(255, 255, 255));
        ano.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ano.setText("0");
        ano.setBorder(null);

        panelRound1.setBackground(new java.awt.Color(0, 119, 182));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        limpiar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        limpiar.setText("Limpiar");
        limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                limpiarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelRound3.setBackground(new java.awt.Color(0, 119, 182));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        calcular.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        calcular.setForeground(new java.awt.Color(255, 255, 255));
        calcular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calcular.setText("Calcular");
        calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                calcularMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calcular, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minuto)
                            .addComponent(hora)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Horas)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(segundo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(55, 55, 55)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(211, 211, 211))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segundo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minuto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1010, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularMousePressed
        // TODO add your handling code here:
        double sg, mts, hrs, ds, ans, r1, r2, r3, r4;
        String pattern = "###,###.#";
        DecimalFormat decimalFormat = new DecimalFormat(pattern);
        
        sg = Integer.parseInt(segundo.getText());
        mts = Integer.parseInt(minuto.getText());
        hrs = Integer.parseInt(hora.getText());
        ds = Integer.parseInt(dia.getText());
        ans = Integer.parseInt(ano.getText());
        //metros
        if(sg!=0 && mts==0 && hrs==0 && ds==0 && ans==0){
            r1 = sg/60;
            r2 = sg/3600;
            r3 = sg/86400;
            r4 = sg/0.0000003154;
            minuto.setText(""+decimalFormat.format(r1)+" mts");
            hora.setText(""+decimalFormat.format(r2)+" hrs");
            dia.setText(""+decimalFormat.format(r3)+" ds");
            ano.setText(""+decimalFormat.format(r4)+" ans");
        }else if(sg==0 && mts!=0 && hrs==0 && ds==0 && ans==0){
            r1 = mts*60;
            r2 = mts/60;
            r3 = mts/1440;
            r4 = mts/525600;
            segundo.setText(""+decimalFormat.format(r1)+" sg");
            hora.setText(""+decimalFormat.format(r2)+" hrs");
            dia.setText(""+decimalFormat.format(r3)+" ds");
            ano.setText(""+decimalFormat.format(r4)+" ans");
        }else if(sg==0 && mts==0 && hrs!=0 && ds==0 && ans==0){
            r1 = hrs*3600;
            r2 = hrs*60;
            r3 = hrs/24;
            r4 = hrs/8760;
            segundo.setText(""+decimalFormat.format(r1)+" sg");
            minuto.setText(""+decimalFormat.format(r2)+" mts");
            dia.setText(""+decimalFormat.format(r3)+" ds");
            ano.setText(""+decimalFormat.format(r4)+" ans");
        }else if(sg==0 && mts==0 && hrs==0 && ds!=0 && ans==0){
            r1 = ds*86400;
            r2 = ds*1440;
            r3 = ds*24;
            r4 = ds/365;
            segundo.setText(""+decimalFormat.format(r1)+" sg");
            minuto.setText(""+decimalFormat.format(r2)+" mts");
            hora.setText(""+decimalFormat.format(r3)+" hrs");
            ano.setText(""+decimalFormat.format(r4)+" ans");
        }else if(sg==0 && mts==0 && hrs==0 && ds==0 && ans!=0){
            r1 = ans*31540000;
            r2 = ans*525600;
            r3 = ans*8760;
            r4 = ans*365;
            segundo.setText(""+decimalFormat.format(r1)+" sg");
            minuto.setText(""+decimalFormat.format(r2)+" mts");
            hora.setText(""+decimalFormat.format(r3)+" hrs");
            dia.setText(""+decimalFormat.format(r4)+" ds");
        }else{
            JOptionPane.showMessageDialog(this, "Por favor introduce un valor, en algún campo.");
        }
        
    }//GEN-LAST:event_calcularMousePressed

    private void limpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarMousePressed
        // TODO add your handling code here:
            segundo.setText("0");
            minuto.setText("0");
            hora.setText("0");
            dia.setText("0");
            ano.setText("0");
    }//GEN-LAST:event_limpiarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Horas;
    private javax.swing.JTextField ano;
    private javax.swing.JPanel background;
    private javax.swing.JLabel calcular;
    private javax.swing.JTextField dia;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel limpiar;
    private javax.swing.JTextField minuto;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound1;
    private com.imbochfckyeah.projects.calculatorphysical.PanelRound panelRound3;
    private javax.swing.JTextField segundo;
    // End of variables declaration//GEN-END:variables
}
